### PR TITLE
fix attributes with indifferent access - fix for #3

### PR DESCRIPTION
**Pull request by fruwe**
prepend needs to be used on the singleton class

(My fault 🙇  )

### CODE REVIEW

**Comment by CGamesPlay** [comment]
Feel free to merge this yourself. I can make a new release after the holidays.

**Comment by fruwe** [comment]
awesome, thanks. Sorry, I missed your kind comment about adding me as collaborator, but it seems that I do still do not have write access. Would you mind to have a look again?

Happy holidays 🎅

**Comment by CGamesPlay** [comment]
I think you have to accept: https://github.com/CGamesPlay/haml_user_tags/invitations

**Comment by fruwe** [comment]
Thanks!

**Pull request merged**
